name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies
        run: |
          cd worker
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run app tests with coverage
        run: |
          cd app
          coverage run -m pytest
          coverage report --fail-under=100

      - name: Run worker tests with coverage
        run: |
          cd worker
          coverage run -m pytest
          coverage report --fail-under=100
